config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root 'pages#index'

  require "sidekiq/web"
  mount Sidekiq::Web => "sidekiq"
  # sessions
  get "signin", to: "sessions#new", as: "sign_in"
  post "signin", to: "sessions#create"
  get "signout", to: "sessions#destroy", as: "sign_out"

  get "signup/", to: "users#new", as: "sign_up"
  get "signup/:affiliate_signup_code", to: "users#new", as: "sign_up_with_affiliate_code"

  get "blog", to: "articles#index", as: "blog"
  get "account", to: "users#show", as: "account"
  get "contact", to: "pages#contact", as: "contact"
  get "careers", to: "pages#careers", as: "careers"
  get "upgrade", to: "pages#upgrade", as: "upgrade"
  get "cancel_membership", to: "subscribers#destroy"
  get "help", to: "pages#help", as: "help"
  get "free", to: "pages#free", as: "free"

  get "error", to: "pages#error", as: "error"

  # help
  get "help/tos", to: "help#tos", as: "tos"
  get "help/privacy_policy", to: "help#privacy_policy", as: "privacy_policy"
  
  post "stripe_webhook_1122", to: "stripe#index"

  post 'stripe_webhook' => 'subscribers#stripe_charge'

  %w(404 422 500 503).each do |code|
    get code, to: "pages#error", code: code
  end

  # games
  get "games", to: "games#index"

  namespace :api do
    namespace :v1 do
      resources :courses
    end
  end

  namespace :games do
    
    scope "word_search", as: "word_search" do
      get "", to: "word_search#index"
      post "found_word", to: "word_search#found_word"
    end

    scope "flash_cards", as: "flash_cards" do
      get "", to: "flash_cards#index"
      post "attempt", to: "flash_cards#attempt", as: "attempt_flash_card"
      post "toggle_options", to: "flash_cards#toggle_options"
    end
  end

  get "email_confirm", to: "email_signups#confirm"

  # downloads goes to download links, only the admin access downloads directly
  get "downloads/:id", to: "download_links#show", as: "download"
  post "downloads/:id/start_download", to: "download_links#start_download", as: "start_download"

  resources :password_resets, only: [:new, :create, :show]
  get "expired_password_token", to: "forgot_passwords#expired"

  resources :forgot_passwords, only: [:create, :new]
  get "forgot_password_confirmation", to: "forgot_passwords#confirm"

  get "my_words", to: "user_vocabulary_words#show"

  resources :password_resets, only: [:show, :create]
  
  resources :users, only: [:create, :edit, :update] do
    collection do
     get "new_account"
   end
  end
  resources :notifications, only: [:index, :show] do
    collection do
      get "check_all"
    end
    member do
      get "toggle"
    end
  end
  resources :article_topics, only: [:show]
  resources :articles, only: [:show] do
    resources :comments, only: [:create] do
      resources :replies
    end
  end
  
  resources :email_signups, only: [:create]

  # regular user
  namespace :help do
    resources :support_tickets
  end

  resources :user_vocabulary_words, only: [:create]
  resources :ebooks, only: [:index, :show]
  resources :affiliates, only: [:index, :show]
  resources :course_levels, only: [:show]
  
  resources :courses, only: [:index, :show] do
    resources :lessons, only: [:show] do
      post "complete", as: "complete_lesson"
      resources :comments do
        resources :replies
      end
      resources :quizzes do
        post "attempt", as: "attempt_quiz"
      end
    end
    member do 
      post "enroll"
    end
  end

  # admin
  namespace :admin do
    resources :articles
    resources :article_topics
    resources :ebooks
    namespace :dashboard do
      resources :videos
      resources :affiliate_payments do
        member do
          post "pay"
        end
      end
      namespace :reports do
        get "/", to: "reports#index", as: "reports"
        get "/payments", to: "reports#payments", as: "payments"
        get "/new_users", to: "reports#new_users", as: "new_users"
        get "/user_actions", to: "reports#user_actions"
        delete "/user_action", to: "reports#delete_user_action"
      end
      resources :notifications do
        collection do
          get "check_all"
        end
        member do
          get "toggle"
        end
      end
      resources :comment_notifications do
        collection do
          get "check_all"
        end
        member do
          get "toggle"
        end
      end
      resources :affiliates do
        resources :affiliate_links
      end
      resources :course_levels
      resources :vocabulary_words do
        collection do
          post "get_related_words"
        end
      end
      resources :levels
      resources :downloads
      get "/", to: "dashboard#index"
    end
    resources :courses do
      # get "/fetch_course_information_from_google_drive", to: "courses#fetch_course_information_from_google_drive"
      resources :units
      member do
        get "/rearrange", to: "courses#rearrange"
        post "/rearrange", to: "courses#post_rearrange"
        post "/import_vocabulary_words", to: "lessons#import_vocabulary_words"
        post "/import_quizzes", to: "courses#import_quizzes"
      end
      resources :lessons do
        resources :vocabulary_words, only: [:update, :destroy]
        member do
          post "/add_existing_vocabulary_word", to: "lessons#add_existing_vocabulary_word"
          post "/import_quiz", to: "lessons#import_quiz"
        end
        resources :quizzes do
          resources :questions do
            resources :choices
          end
        end
      end
    end
    resources :email_signups, only: [:index, :destroy]
    resources :users
    resources :categories
  end
  
  resources :subscribers


  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < AdminController

  before_action :set_quiz, only: [:show, :update, :edit, :destroy]
  before_action :set_lesson, only: [:show, :update, :edit, :new, :create, :destroy]
  before_action :set_course, only: [:show, :update, :edit, :new, :create, :destroy]
  before_action :set_choice, only: [:edit]

  add_breadcrumb "Admin", :root_path
  add_breadcrumb "Courses", :admin_courses_path
  
  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(lesson_id: @lesson.id)
    if @quiz.save
      flash[:success] = "Quiz was created"
      redirect_to edit_admin_course_lesson_quiz_path(Course.find_by(slug: params[:course_id]), @lesson, @quiz)
    else
      flash.now[:danger] = "There was a problem and the quiz was not saved"
      render :new
    end
  end

  def destroy
    @quiz.questions.each do |question|
      question.choices.destroy_all
    end
    @quiz.questions.destroy_all
    @quiz.destroy
    
    flash[:success] = "Quiz was deleted."
    redirect_to edit_admin_course_lesson_path(@course, @lesson)
  end

  def edit

    add_breadcrumb @course.name, admin_course_path(@course)
    add_breadcrumb @lesson.name, admin_course_lesson_path(@course, @lesson)

    @question = Question.new
  end

  private

  def set_choice
    @choice = Choice.new
  end

  def set_quiz
    @quiz = Quiz.find_by(slug: params[:id])
  end

  def set_lesson
    @lesson = Lesson.find_by(slug: params[:lesson_id])
  end

  def set_course
    @course = Course.find_by(slug: params[:course_id])
  end

  def quiz_params
    params.require(:quiz).permit!
  end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  before_action :require_paid_membership

  def attempt
    @course = Course.find_by(slug: params[:course_id])
    @lesson = Lesson.find_by(slug: params[:lesson_id])
    @quiz = Quiz.find_by(slug: params[:quiz_id])

    if params[:questions]
      questions_and_answers_array = []

      params[:questions].each do |question_and_answer_pair|
        choice = Choice.find(question_and_answer_pair[1])
        questions_and_answers_array << [choice.question, choice]
      end
      
      current_user.attempt_quiz(@quiz, questions_and_answers_array)

      flash[:success] = "成功嘗試測驗."
      # flash[:success] = "Successfully attempted quiz."
    else
      flash[:danger] = "你沒有回答任何問題。"
      # flash[:danger] = "You did not answer any questions."
    end
      redirect_to course_lesson_path(@course, @lesson)
  end
  
end

app/views/admin/quizzes/_choice.html.haml
%li.question_choice_admin{id: "choice-#{choice.id}"}
  .row
    .col-sm-5
      = choice.body
    .col-sm-2
      - if choice.correct?
        %i.fa.fa-check.green-bkg
      - else
        %strong.red_x X
    .col-sm-2
      = link_to admin_course_lesson_quiz_question_choice_path(@course, @lesson, @quiz, question, choice), method: "DELETE", remote: true, data: {confirm: "Are you sure you want to delete this choice?"} do
        .btn.btn-danger Delete
    .col-sm-2
      .btn.btn-primary.question_choice_edit_button Edit


%li.question_choice_form{id: "choice-form-#{choice.id}"}
  = bootstrap_form_for [:admin, choice.question.quiz.lesson.course, choice.question.quiz.lesson, choice.question.quiz, choice.question, choice], remote: true do |f|
    = f.text_field :body
    .row
      .col-sm-6
        = label :correct, 'Correct Answer', for: question.slug + "-true"
        = f.radio_button :correct, true, checked: (choice.correct?), inline: true, class: "radio-inline", id: question.slug + "-true"
      .col-sm-6
        = label :correct, 'Not Correct Answer', for: question.slug + "-false"
        = f.radio_button :correct, false, checked: (!choice.correct?), inline: true, class: "radio-inline", id: question.slug + "-false"
    = f.submit "Save choice", class: "btn btn-primary"

app/views/admin/quizzes/_question.html.haml
.quiz_question{id: "question-#{question.slug}"}
  .row
    .col-sm-8
      %button.btn.btn-info{"data-target" => "#question-collapse-#{question.slug}", "data-toggle" => "collapse", :type => "button"} Edit
      .collapse{id: "question-collapse-#{question.slug}"}

        = bootstrap_form_for [:admin, @lesson.course, @lesson, @quiz, question], method: "PUT", remote: true do |f|
          = f.file_field :image_url, label: "Image", class: "btn btn-file"
          = f.text_area :body, class: "form-control"
          = f.text_field :value
          = f.submit "Update", class: "btn btn-primary btn-xs"
        %hr/
        %br/
      .quiz_question_container{id: "question-#{question.slug}"}
        = question.body.html_safe
      %br/
      %strong= "Value: #{question.value}"
  %br/
  - unless question.image_url.blank?
    .row
      .col-sm-12
        =image_tag(question.image_url)

  %ol.question_choices
    %h3.center Choices
    %hr/
    - question.choices.each do |choice|
      %div{id: "choice-container-#{choice.id}"}
        = render "admin/quizzes/choice", choice: choice, question: question

  %h3.center New Choice
  = bootstrap_form_for [:admin, @course, @lesson, @quiz, question, Choice.new], remote: true do |f|
    = f.text_field :body
    .row
      .col-sm-6
        = label :correct, 'Correct Answer', for: question.slug + "-true"
        = f.radio_button :correct, true, checked: false, inline: true, class: "radio-inline", id: question.slug + "-true"
      .col-sm-6
        = label :correct, 'Not Correct Answer', for: question.slug + "-false"
        = f.radio_button :correct, false, checked: true, inline: true, class: "radio-inline", id: question.slug + "-false"
    = f.submit "Add choice", class: "btn btn-primary"
    = link_to admin_course_lesson_quiz_question_path(@course, @lesson, @quiz, question), method: :delete, remote: true, data: {confirm: "Are you sure you want to delete this question?"} do
      .btn.btn-danger.pull-right Delete Question

app/views/admin/quizzes/edit.html.haml
%h3= "Editing quiz for #{@lesson.name} in #{@course.name} course"
= link_to edit_admin_course_lesson_path(@course, @lesson) do
  .small Back to edit lesson
.row
  .container
    .row
      %h5 New Question
      = bootstrap_form_for([:admin, @course, @lesson, @quiz, @question], remote: true) do |f|
        = f.file_field :image_url, label: "Image", class: "btn btn-file"
        = f.text_area :body, class: "form-control"

        .row
          .col-sm-2
            = f.text_field :value, value: 10
        = f.submit "Add Question", class: "btn btn-primary"
    .col-sm-7
      %h5 Questions for this lesson:
      #editing_questions_container
        - @quiz.questions.order("created_at DESC").each do |question|
          %div{id: "question_container-#{question.slug}"}
            = render "question", question: question

app/views/admin/quizzes/new.html.haml
%h1= "New quiz for #{@lesson.name}"

app/views/admin/quizzes/question.js.erb
alert('created question')